specs_dir: data/tiered_imagenet/specs
distances_dir: data/tiered_imagenet/distances
models_dir: data/tiered_imagenet/models
metrics_dir: data/tiered_imagenet/metrics
tb_logs_dir: data/tiered_imagenet/tb_logs
logs_dir: data/tiered_imagenet/logs
testbeds_dir: data/tiered_imagenet/testbeds

device: cuda:2


testbed:
  n_tasks: 5000
  n_way: 5
  n_query: 10
  n_shot:
  - 1
  - 5

testbeds_grid:
- 1_shot
- 5_shot
- uniform_1_shot
- uniform_5_shot

model:
  weights: data/tiered_imagenet/models/resnet12_tiered_imagenet_classic.tar
  method: PrototypicalNetworks
